[project]
name = "rostr"
version = "0.1.0"
description = ""
authors = [
    {name = "CK",email = "ckunthe@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer (>=0.24.0,<0.25.0)"
]

[tool.poetry]
packages = [{include = "rostr", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rostr = "rostr.main:app"
