[project]
name = "rostr"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
authors = [{ name = "CK", email = "ckunthe@gmail.com" }]
dependencies = ["typer (>=0.24.0,<0.25.0)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "rostr", from = "src" }]

[tool.poetry.scripts]
rostr = "rostr.main:app"
